[workspace]
members = [
    "crates/praborrow-core",
    "crates/praborrow-defense",
    "crates/praborrow-logistics",
    "crates/praborrow-diplomacy",
    "crates/praborrow-lease",
    "crates/praborrow-sidl",
    "crates/praborrow-macros",
    "crates/praborrow-prover",
    "crates/praborrow",
    "xtask",
]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2024"
authors = ["ireddragonicy"]
license = "MIT"
repository = "https://github.com/ireddragonicy/PraBorrow"

