[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
xshell = "0.2"
anyhow = "1.0"
owo-colors = "4.2" # Make it look expert with colors
indicatif = "0.18.3"
toml_edit = "0.22"
